# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-DisableForm
version:      0.01
version_from: lib/Template/Plugin/DisableForm.pm
installdirs:  site
requires:
    HTML::DisableForm:             0
    Template:                      0
    Template::Plugin::Filter:      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
